### PR TITLE
Complete capstone

### PR DESCRIPTION
**Pull request by Yacoubou-seidou**
### Complete capstone
- Splash screen
The user should be able to register in the app with full name, email and password.
The user can log into the app using email and password.
If the user is not logged in, they can't access pages that require the user to be logged in
- Home page (categories page)
When the user logs in, they are presented with the categories page.
For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
- Transactions page
For a given category, the list of transactions is presented, ordered by the most recent.
At the top of the page the user could see the total amount for the category.
There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
When the user clicks on the "Back" button (<), the user navigates to the home page.
- "Add a new category" page
The user fills out a form to create a new category, indicating their name and icon.
The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
When the user clicks on the "Back" button (<), the user navigates to the home page.
- "Add a new transaction" page
The user fills out a form to create a new transaction with:
name
amount
categories 
The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.
- Testing requirements
 Unit and integration tests for all the most important components of the application.
- Technical requirements
 use Postgres as your database.
 use devise for authentication.
 validate all user input to make sure that anyone with bad intentions cannot compromise your app.
 use a view template engine of my choice (.erb).
The project is deployed and accessible online.
The database schema reflect the diagram
- Presentation video create

### CODE REVIEW

**Review by franclobo — COMMENTED** [review]
Hi @Yacoubou-seidou, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has the wrong Git flow, you must create the PR to merge the changes from the dev branch into the main branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Yacoubou-seidou** [comment]
@franclobo Sorry but I am confused the preview reviewer tell me to do it this way check the PR https://github.com/Yacoubou-seidou/Kondona/pull/6

**Comment by franclobo** [comment]
Hello @Yacoubou-seidou 

I'm sorry for my mistake, this is a solo capstone project:

1. For group capstone projects the correct flow for requesting reviews is Github flow which means dev merging to main. (In this case,
2. For solo capstone projects the flow for requesting reviews is Gitflow which means feature branch merging to dev.

**Review by franclobo — APPROVED** [review]
Hi @Yacoubou-seidou, 

# STATUS: APPROVED 😃 

leonardo-dicaprio-leo-dicaprio

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlight

- Unit and integration tests passed ✔️ 
- Use PostgreSQL ✔️ 
- Use device for authentication and cancancan for authorization ✔️ 
- Good UI and UX ✔️ 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
